<a href="https://colab.research.google.com/github/Ke-erah/Starting-Portfolio/blob/master/Track_Sales_Information.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%capture
%load_ext sql
%sql sqlite:///chinook.db

'Connected: None@chinook.db'

# Data Overview

In [ ]:
%%sql
SELECT
    name,
    type
FROM sqlite_master
WHERE type IN ("table","view");

Done.

[('album', 'table'),
 ('artist', 'table'),
 ('customer', 'table'),
 ('employee', 'table'),
 ('genre', 'table'),
 ('invoice', 'table'),
 ('invoice_line', 'table'),
 ('media_type', 'table'),
 ('playlist', 'table'),
 ('playlist_track', 'table'),
 ('track', 'table'),
 ('sales_data', 'view'),
 ('summary', 'view')]

In [ ]:
%%sql
SELECT * FROM customer

Done.

[(1, 'Luís', 'Gonçalves', 'Embraer - Empresa Brasileira de Aeronáutica S.A.', 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', '+55 (12) 3923-5555', '+55 (12) 3923-5566', 'luisg@embraer.com.br', 3),
 (2, 'Leonie', 'Köhler', None, 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', '+49 0711 2842222', None, 'leonekohler@surfeu.de', 5),
 (3, 'François', 'Tremblay', None, '1498 rue Bélanger', 'Montréal', 'QC', 'Canada', 'H2G 1A7', '+1 (514) 721-4711', None, 'ftremblay@gmail.com', 3),
 (4, 'Bjørn', 'Hansen', None, 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', '+47 22 44 22 22', None, 'bjorn.hansen@yahoo.no', 4),
 (5, 'František', 'Wichterlová', 'JetBrains s.r.o.', 'Klanova 9/506', 'Prague', None, 'Czech Republic', '14700', '+420 2 4172 5555', '+420 2 4172 5555', 'frantisekw@jetbrains.com', 4),
 (6, 'Helena', 'Holý', None, 'Rilská 3174/6', 'Prague', None, 'Czech Republic', '14300', '+420 2 4177 0449', None, 'hholy@gmail.com', 5),
 (7, 'Astrid', 'Gruber', None, 'Rotenturmstraße 4, 1010 Innere Stadt', 'Vienne', None, 'Austria', '1010', '+43 01 5134505', None, 'astrid.gruber@apple.at', 5),
 (8, 'Daan', 'Peeters', None, 'Grétrystraat 63', 'Brussels', None, 'Belgium', '1000', '+32 02 219 03 03', None, 'daan_peeters@apple.be', 4),
 (9, 'Kara', 'Nielsen', None, 'Sønder Boulevard 51', 'Copenhagen', None, 'Denmark', '1720', '+453 3331 9991', None, 'kara.nielsen@jubii.dk', 4),
 (10, 'Eduardo', 'Martins', 'Woodstock Discos', 'Rua Dr. Falcão Filho, 155', 'São Paulo', 'SP', 'Brazil', '01007-010', '+55 (11) 3033-5446', '+55 (11) 3033-4564', 'eduardo@woodstock.com.br', 4),
 (11, 'Alexandre', 'Rocha', 'Banco do Brasil S.A.', 'Av. Paulista, 2022', 'São Paulo', 'SP', 'Brazil', '01310-200', '+55 (11) 3055-3278', '+55 (11) 3055-8131', 'alero@uol.com.br', 5),
 (12, 'Roberto', 'Almeida', 'Riotur', 'Praça Pio X, 119', 'Rio de Janeiro', 'RJ', 'Brazil', '20040-020', '+55 (21) 2271-7000', '+55 (21) 2271-7070', 'roberto.almeida@riotur.gov.br', 3),
 (13, 'Fernanda', 'Ramos', None, 'Qe 7 Bloco G', 'Brasília', 'DF', 'Brazil', '71020-677', '+55 (61) 3363-5547', '+55 (61) 3363-7855', 'fernadaramos4@uol.com.br', 4),
 (14, 'Mark', 'Philips', 'Telus', '8210 111 ST NW', 'Edmonton', 'AB', 'Canada', 'T6G 2C7', '+1 (780) 434-4554', '+1 (780) 434-5565', 'mphilips12@shaw.ca', 5),
 (15, 'Jennifer', 'Peterson', 'Rogers Canada', '700 W Pender Street', 'Vancouver', 'BC', 'Canada', 'V6C 1G8', '+1 (604) 688-2255', '+1 (604) 688-8756', 'jenniferp@rogers.ca', 3),
 (16, 'Frank', 'Harris', 'Google Inc.', '1600 Amphitheatre Parkway', 'Mountain View', 'CA', 'USA', '94043-1351', '+1 (650) 253-0000', '+1 (650) 253-0000', 'fharris@google.com', 4),
 (17, 'Jack', 'Smith', 'Microsoft Corporation', '1 Microsoft Way', 'Redmond', 'WA', 'USA', '98052-8300', '+1 (425) 882-8080', '+1 (425) 882-8081', 'jacksmith@microsoft.com', 5),
 (18, 'Michelle', 'Brooks', None, '627 Broadway', 'New York', 'NY', 'USA', '10012-2612', '+1 (212) 221-3546', '+1 (212) 221-4679', 'michelleb@aol.com', 3),
 (19, 'Tim', 'Goyer', 'Apple Inc.', '1 Infinite Loop', 'Cupertino', 'CA', 'USA', '95014', '+1 (408) 996-1010', '+1 (408) 996-1011', 'tgoyer@apple.com', 3),
 (20, 'Dan', 'Miller', None, '541 Del Medio Avenue', 'Mountain View', 'CA', 'USA', '94040-111', '+1 (650) 644-3358', None, 'dmiller@comcast.com', 4),
 (21, 'Kathy', 'Chase', None, '801 W 4th Street', 'Reno', 'NV', 'USA', '89503', '+1 (775) 223-7665', None, 'kachase@hotmail.com', 5),
 (22, 'Heather', 'Leacock', None, '120 S Orange Ave', 'Orlando', 'FL', 'USA', '32801', '+1 (407) 999-7788', None, 'hleacock@gmail.com', 4),
 (23, 'John', 'Gordon', None, '69 Salem Street', 'Boston', 'MA', 'USA', '2113', '+1 (617) 522-1333', None, 'johngordon22@yahoo.com', 4),
 (24, 'Frank', 'Ralston', None, '162 E Superior Street', 'Chicago', 'IL', 'USA', '60611', '+1 (312) 332-3232', None, 'fralston@gmail.com', 3),
 (25, 'Victor', 'Stevens', None, '319 N. Frances Street', 'Madison', 'WI', 'USA', '53703', '+1 (608) 257-0597', None, 'vstevens@yahoo.com', 5),
 (26, 'Richard', 'Cunningham', None, '2211 W Berry Street', 'Fort Worth', 'TX', 'USA', '76110', '+1 (817) 924-7272', None, 'ricunningham@hotmail.com', 4),
 (27, 'Patrick', 'Gray', None, '1033 N Park Ave', 'Tucson', 'AZ', 'USA', '85719', '+1 (520) 622-4200', None, 'patrick.gray@aol.com', 4),
 (28, 'Julia', 'Barnett', None, '302 S 700 E', 'Salt Lake City', 'UT', 'USA', '84102', '+1 (801) 531-7272', None, 'jubarnett@gmail.com', 5),
 (29, 'Robert', 'Brown', None, '796 Dundas Street West', 'Toronto', 'ON', 'Canada', 'M6J 1V1', '+1 (416) 363-8888', None, 'robbrown@shaw.ca', 3),
 (30, 'Edward', 'Francis', None, '230 Elgin Street', 'Ottawa', 'ON', 'Canada', 'K2P 1L7', '+1 (613) 234-3322', None, 'edfrancis@yachoo.ca', 3),
 (31, 'Martha', 'Silk', None, '194A Chain Lake Drive', 'Halifax', 'NS', 'Canada', 'B3S 1C5', '+1 (902) 450-0450', None, 'marthasilk@gmail.com', 5),
 (32, 'Aaron', 'Mitchell', None, '696 Osborne Street', 'Winnipeg', 'MB', 'Canada', 'R3L 2B9', '+1 (204) 452-6452', None, 'aaronmitchell@yahoo.ca', 4),
 (33, 'Ellie', 'Sullivan', None, '5112 48 Street', 'Yellowknife', 'NT', 'Canada', 'X1A 1N6', '+1 (867) 920-2233', None, 'ellie.sullivan@shaw.ca', 3),
 (34, 'João', 'Fernandes', None, 'Rua da Assunção 53', 'Lisbon', None, 'Portugal', None, '+351 (213) 466-111', None, 'jfernandes@yahoo.pt', 4),
 (35, 'Madalena', 'Sampaio', None, 'Rua dos Campeões Europeus de Viena, 4350', 'Porto', None, 'Portugal', None, '+351 (225) 022-448', None, 'masampaio@sapo.pt', 4),
 (36, 'Hannah', 'Schneider', None, 'Tauentzienstraße 8', 'Berlin', None, 'Germany', '10789', '+49 030 26550280', None, 'hannah.schneider@yahoo.de', 5),
 (37, 'Fynn', 'Zimmermann', None, 'Berger Straße 10', 'Frankfurt', None, 'Germany', '60316', '+49 069 40598889', None, 'fzimmermann@yahoo.de', 3),
 (38, 'Niklas', 'Schröder', None, 'Barbarossastraße 19', 'Berlin', None, 'Germany', '10779', '+49 030 2141444', None, 'nschroder@surfeu.de', 3),
 (39, 'Camille', 'Bernard', None, '4, Rue Milton', 'Paris', None, 'France', '75009', '+33 01 49 70 65 65', None, 'camille.bernard@yahoo.fr', 4),
 (40, 'Dominique', 'Lefebvre', None, '8, Rue Hanovre', 'Paris', None, 'France', '75002', '+33 01 47 42 71 71', None, 'dominiquelefebvre@gmail.com', 4),
 (41, 'Marc', 'Dubois', None, '11, Place Bellecour', 'Lyon', None, 'France', '69002', '+33 04 78 30 30 30', None, 'marc.dubois@hotmail.com', 5),
 (42, 'Wyatt', 'Girard', None, '9, Place Louis Barthou', 'Bordeaux', None, 'France', '33000', '+33 05 56 96 96 96', None, 'wyatt.girard@yahoo.fr', 3),
 (43, 'Isabelle', 'Mercier', None, '68, Rue Jouvence', 'Dijon', None, 'France', '21000', '+33 03 80 73 66 99', None, 'isabelle_mercier@apple.fr', 3),
 (44, 'Terhi', 'Hämäläinen', None, 'Porthaninkatu 9', 'Helsinki', None, 'Finland', '00530', '+358 09 870 2000', None, 'terhi.hamalainen@apple.fi', 3),
 (45, 'Ladislav', 'Kovács', None, 'Erzsébet krt. 58.', 'Budapest', None, 'Hungary', 'H-1073', None, None, 'ladislav_kovacs@apple.hu', 3),
 (46, 'Hugh', "O'Reilly", None, '3 Chatham Street', 'Dublin', 'Dublin', 'Ireland', None, '+353 01 6792424', None, 'hughoreilly@apple.ie', 3),
 (47, 'Lucas', 'Mancini', None, 'Via Degli Scipioni, 43', 'Rome', 'RM', 'Italy', '00192', '+39 06 39733434', None, 'lucas.mancini@yahoo.it', 5),
 (48, 'Johannes', 'Van der Berg', None, 'Lijnbaansgracht 120bg', 'Amsterdam', 'VV', 'Netherlands', '1016', '+31 020 6223130', None, 'johavanderberg@yahoo.nl', 5),
 (49, 'Stanisław', 'Wójcik', None, 'Ordynacka 10', 'Warsaw', None, 'Poland', '00-358', '+48 22 828 37 39', None, 'stanisław.wójcik@wp.pl', 4),
 (50, 'Enrique', 'Muñoz', None, 'C/ San Bernardo 85', 'Madrid', None, 'Spain', '28015', '+34 914 454 454', None, 'enrique_munoz@yahoo.es', 5),
 (51, 'Joakim', 'Johansson', None, 'Celsiusg. 9', 'Stockholm', None, 'Sweden', '11230', '+46 08-651 52 52', None, 'joakim.johansson@yahoo.se', 5),
 (52, 'Emma', 'Jones', None, '202 Hoxton Street', 'London', None, 'United Kingdom', 'N1 5LH', '+44 020 7707 0707', None, 'emma_jones@hotmail.com', 3),
 (53, 'Phil', 'Hughes', None, '113 Lupus St', 'London', None, 'United Kingdom', 'SW1V 3EN', '+44 020 7976 5722', None, 'phil.hughes@gmail.com', 3),
 (54, 'Steve', 'Murray', None, '110 Raeburn Pl', 'Edinburgh ', None, 'United Kingdom', 'EH4 1HH', '+44 0131 315 3300', None, 'steve.murray@yahoo.uk', 5),
 (55, 'Mark', 'Taylor', None, '421 Bourke Street', 'Sidney', 'NSW', 'Australia', '2010', '+61 (02) 9332 3633', None, 'mark.taylor@yahoo.au', 4),
 (56, 'Diego', 'Gutiérrez', None, '307 Macacha Güemes', 'Buenos Aires', None, 'Argentina', '1106', '+54 (0)11 4311 4333', None, 'diego.gutierrez@yahoo.ar', 4),
 (57, 'Luis', 'Rojas', None, 'Calle Lira, 198', 'Santiago', None, 'Chile', None, '+56 (0)2 635 4444', None, 'luisrojas@yahoo.cl', 5),
 (58, 'Manoj', 'Pareek', None, '12,Community Centre', 'Delhi', None, 'India', '110017', '+91 0124 39883988', None, 'manoj.pareek@rediff.com', 3),
 (59, 'Puja', 'Srivastava', None, '3,Raj Bhavan Road', 'Bangalore', None, 'India', '560001', '+91 080 22289999', None, 'puja_srivastava@yahoo.in', 3)]

# Selecting Albums to Purchase

A query to find out which genres sell the most tracks in the USA

In [ ]:
%%sql
WITH usa AS (SELECT c.customer_id, c.country, i.invoice_id, i.total
FROM customer AS c INNER JOIN invoice AS i
ON c.customer_id=i.customer_id
WHERE country='USA'), 

track_qty_usa AS (SELECT u.*, il.track_id, il.quantity
FROM usa AS u
LEFT JOIN invoice_line AS il
ON u.invoice_id=il.invoice_id),

genre_id_usa AS (SELECT tqu.*, t.genre_id
FROM track_qty_usa AS tqu 
LEFT JOIN track AS t
ON tqu.track_id=t.track_id),

genre_usa AS (SELECT giu.country, SUM(giu.quantity) AS quantity, g.name AS genre
FROM genre_id_usa AS giu
INNER JOIN genre AS g
ON giu.genre_id=g.genre_id
GROUP BY g.name)

SELECT genre, quantity, 
CAST(quantity AS Float)/(SELECT SUM(quantity) FROM genre_usa) AS percentage
FROM genre_usa AS gu
ORDER BY quantity DESC

Done.

[('Rock', 561, 0.5337773549000951),
 ('Alternative & Punk', 130, 0.12369172216936251),
 ('Metal', 124, 0.11798287345385347),
 ('R&B/Soul', 53, 0.05042816365366318),
 ('Blues', 36, 0.03425309229305423),
 ('Alternative', 35, 0.03330161750713606),
 ('Latin', 22, 0.02093244529019981),
 ('Pop', 22, 0.02093244529019981),
 ('Hip Hop/Rap', 20, 0.019029495718363463),
 ('Jazz', 14, 0.013320647002854425),
 ('Easy Listening', 13, 0.012369172216936251),
 ('Reggae', 6, 0.005708848715509039),
 ('Electronica/Dance', 5, 0.004757373929590866),
 ('Classical', 4, 0.003805899143672693),
 ('Heavy Metal', 3, 0.0028544243577545195),
 ('Soundtrack', 2, 0.0019029495718363464),
 ('TV Shows', 1, 0.0009514747859181732)]

From the above table/finding, it can be seen that the order of popularity of the genres in the USA (based on the new tracks) is as follows:
1. Punk
2. Blues
3. Pop
4. Hip-hop

Hence, the recommendation would be to select artists: 
1. Red Tone(Punk)
2.Slim Jim Bites(Blues)
3.Meteor and the Girls(Pop)

# Analyzing Employees Sales Performance

In [ ]:
%%sql
SELECT e.first_name||' '||e.last_name employee_name,
e.title employee_title, e.hire_date, sum(i.total) total_sales
FROM employee AS e
INNER JOIN customer AS c
ON e.employee_id=c.support_rep_id
INNER JOIN invoice AS i
ON c.customer_id=i.customer_id
WHERE e.title='Sales Support Agent'
GROUP BY employee_name

Done.

[('Jane Peacock', 'Sales Support Agent', '2017-04-01 00:00:00', 1731.5100000000039),
 ('Margaret Park', 'Sales Support Agent', '2017-05-03 00:00:00', 1584.0000000000034),
 ('Steve Johnson', 'Sales Support Agent', '2017-10-17 00:00:00', 1393.920000000002)]

The sales agent with the highest sales (Jane Peacock) has been working for the company for a longer period than other sales agents

# Analyzing Sales by Country

In [ ]:
%%sql
CREATE VIEW sales_data AS
SELECT c.customer_id, c.country, i.total, il.quantity FROM customer c
INNER JOIN invoice i
ON c.customer_id=i.customer_id
INNER JOIN invoice_line il
ON i.invoice_id=il.invoice_id

(sqlite3.OperationalError) table sales_data already exists
[SQL: CREATE VIEW sales_data AS
SELECT c.customer_id, c.country, i.total, il.quantity FROM customer c
INNER JOIN invoice i
ON c.customer_id=i.customer_id
INNER JOIN invoice_line il
ON i.invoice_id=il.invoice_id]
(Background on this error at: http://sqlalche.me/e/e3q8)

In [ ]:
%%sql
DROP VIEW sales_data

Done.

[]

In [ ]:
%%sql
CREATE VIEW sales_data AS 
SELECT COUNT(DISTINCT(c.customer_id)) customer_count,
COUNT(DISTINCT(i.invoice_id)) invoice_count,
c.country, SUM(il.unit_price) total_sales FROM customer c
INNER JOIN invoice i
ON c.customer_id=i.customer_id
INNER JOIN invoice_line il
ON i.invoice_id=il.invoice_id
GROUP BY country

Done.

[]

In [ ]:
%%sql
CREATE VIEW summary AS 
SELECT new_country, SUM(customer_count) customer_count, 
SUM(total_sales) total_sales, total_sales/customer_count avg_sales,
total_sales/invoice_count ag_order FROM 
(
    SELECT sd.*, 
    CASE
    WHEN sd.customer_count=1 THEN 'Other'
    Else sd.country
    END AS new_country
    FROM sales_data sd)
GROUP BY new_country
ORDER BY total_sales DESC

(sqlite3.OperationalError) table summary already exists
[SQL: CREATE VIEW summary AS
SELECT new_country, SUM(customer_count) customer_count,
SUM(total_sales) total_sales, total_sales/customer_count avg_sales,
total_sales/invoice_count ag_order FROM
(
    SELECT sd.*,
    CASE
    WHEN sd.customer_count=1 THEN 'Other'
    Else sd.country
    END AS new_country
    FROM sales_data sd)
GROUP BY new_country
ORDER BY total_sales DESC]
(Background on this error at: http://sqlalche.me/e/e3q8)

In [ ]:
%%sql
SELECT new_country AS country_name, customer_count, total_sales,
avg_sales, ag_order AS avg_order FROM 
(
    SELECT s.*, 
    CASE
    WHEN s.new_country='Other' THEN 1
    ELSE 0
    END AS sort
    FROM summary s
)
ORDER BY sort

Done.

[('USA', 13, 1040.490000000008, 80.03769230769292, 7.942671755725252),
 ('Canada', 8, 535.5900000000034, 66.94875000000043, 7.047236842105309),
 ('Brazil', 5, 427.68000000000245, 85.53600000000048, 7.011147540983647),
 ('France', 5, 389.0700000000021, 77.81400000000042, 7.781400000000042),
 ('Germany', 4, 334.6200000000016, 83.6550000000004, 8.161463414634186),
 ('Czech Republic', 2, 273.24000000000103, 136.62000000000052, 9.108000000000034),
 ('United Kingdom', 3, 245.52000000000078, 81.84000000000026, 8.768571428571457),
 ('Portugal', 2, 185.13000000000022, 92.56500000000011, 6.3837931034482835),
 ('India', 2, 183.1500000000002, 91.5750000000001, 8.72142857142858),
 ('Other', 15, 1094.9399999999994, 75.23999999999998, 7.523999999999998)]

# Albums vs Individual Tracks

In [ ]:
%%sql
CREATE VIEW track_sales AS 
SELECT * FROM invoice_line il INNER JOIN track t ON il.track_id=t.track_id

Done.

[]

In [ ]:
%%sql
SELECT * FROM track_sales LIMIT 1;

Done.

[(1, 1, 1158, 0.99, 1, 1158, 'Right Next Door to Hell', 91, 2, 1, None, 182321, 3175950, 0.99)]

In [ ]:
%%sql
SELECT track_id FROM track_sales
EXCEPT
SELECT album_id FROM track_sales

Done.

[(12,),
 (25,),
 (28,),
 (29,),
 (31,),
 (32,),
 (45,),
 (51,),
 (52,),
 (53,),
 (60,),
 (68,),
 (71,),
 (161,),
 (165,),
 (172,),
 (201,),
 (202,),
 (208,),
 (219,),
 (226,),
 (228,),
 (229,),
 (298,),
 (301,),
 (337,),
 (340,),
 (341,),
 (342,),
 (346,),
 (348,),
 (349,),
 (350,),
 (383,),
 (392,),
 (402,),
 (409,),
 (410,),
 (411,),
 (413,),
 (415,),
 (419,),
 (420,),
 (421,),
 (422,),
 (423,),
 (424,),
 (425,),
 (426,),
 (427,),
 (428,),
 (429,),
 (430,),
 (431,),
 (432,),
 (433,),
 (434,),
 (435,),
 (436,),
 (437,),
 (438,),
 (439,),
 (440,),
 (441,),
 (442,),
 (443,),
 (444,),
 (445,),
 (446,),
 (447,),
 (448,),
 (449,),
 (450,),
 (451,),
 (452,),
 (453,),
 (454,),
 (455,),
 (459,),
 (461,),
 (465,),
 (468,),
 (469,),
 (470,),
 (472,),
 (473,),
 (474,),
 (475,),
 (476,),
 (477,),
 (478,),
 (479,),
 (480,),
 (481,),
 (482,),
 (483,),
 (484,),
 (485,),
 (486,),
 (487,),
 (488,),
 (492,),
 (496,),
 (510,),
 (514,),
 (517,),
 (524,),
 (528,),
 (529,),
 (530,),
 (531,),
 (532,),
 (533,),
 (534,),
 (535,),
 (536,),
 (537,),
 (538,),
 (539,),
 (540,),
 (541,),
 (542,),
 (544,),
 (545,),
 (546,),
 (548,),
 (553,),
 (571,),
 (572,),
 (573,),
 (574,),
 (577,),
 (579,),
 (580,),
 (585,),
 (587,),
 (592,),
 (593,),
 (594,),
 (597,),
 (599,),
 (600,),
 (602,),
 (604,),
 (605,),
 (608,),
 (609,),
 (610,),
 (611,),
 (612,),
 (614,),
 (615,),
 (619,),
 (620,),
 (622,),
 (675,),
 (676,),
 (681,),
 (682,),
 (684,),
 (686,),
 (687,),
 (688,),
 (689,),
 (690,),
 (691,),
 (692,),
 (693,),
 (695,),
 (696,),
 (697,),
 (698,),
 (699,),
 (700,),
 (701,),
 (702,),
 (703,),
 (704,),
 (705,),
 (706,),
 (707,),
 (708,),
 (709,),
 (710,),
 (711,),
 (712,),
 (713,),
 (714,),
 (719,),
 (739,),
 (740,),
 (748,),
 (749,),
 (750,),
 (751,),
 (755,),
 (757,),
 (768,),
 (771,),
 (773,),
 (778,),
 (781,),
 (784,),
 (787,),
 (788,),
 (794,),
 (795,),
 (800,),
 (802,),
 (803,),
 (804,),
 (807,),
 (808,),
 (809,),
 (810,),
 (811,),
 (812,),
 (813,),
 (814,),
 (815,),
 (818,),
 (819,),
 (822,),
 (826,),
 (827,),
 (828,),
 (829,),
 (830,),
 (831,),
 (832,),
 (833,),
 (834,),
 (836,),
 (837,),
 (839,),
 (840,),
 (841,),
 (851,),
 (857,),
 (861,),
 (875,),
 (891,),
 (892,),
 (893,),
 (894,),
 (895,),
 (896,),
 (897,),
 (898,),
 (899,),
 (900,),
 (901,),
 (902,),
 (903,),
 (904,),
 (905,),
 (906,),
 (907,),
 (908,),
 (910,),
 (911,),
 (913,),
 (914,),
 (915,),
 (916,),
 (917,),
 (918,),
 (919,),
 (920,),
 (921,),
 (922,),
 (923,),
 (925,),
 (928,),
 (931,),
 (932,),
 (933,),
 (937,),
 (940,),
 (943,),
 (944,),
 (948,),
 (950,),
 (952,),
 (955,),
 (963,),
 (968,),
 (969,),
 (970,),
 (973,),
 (979,),
 (989,),
 (990,),
 (991,),
 (992,),
 (993,),
 (995,),
 (996,),
 (997,),
 (998,),
 (999,),
 (1000,),
 (1001,),
 (1002,),
 (1003,),
 (1004,),
 (1005,),
 (1006,),
 (1007,),
 (1008,),
 (1009,),
 (1010,),
 (1011,),
 (1012,),
 (1013,),
 (1014,),
 (1015,),
 (1016,),
 (1017,),
 (1018,),
 (1019,),
 (1020,),
 (1021,),
 (1022,),
 (1023,),
 (1024,),
 (1025,),
 (1026,),
 (1027,),
 (1028,),
 (1029,),
 (1030,),
 (1031,),
 (1032,),
 (1033,),
 (1034,),
 (1035,),
 (1036,),
 (1037,),
 (1038,),
 (1039,),
 (1040,),
 (1041,),
 (1042,),
 (1043,),
 (1044,),
 (1045,),
 (1046,),
 (1047,),
 (1048,),
 (1049,),
 (1050,),
 (1051,),
 (1052,),
 (1053,),
 (1054,),
 (1055,),
 (1056,),
 (1058,),
 (1064,),
 (1074,),
 (1079,),
 (1091,),
 (1094,),
 (1095,),
 (1101,),
 (1102,),
 (1103,),
 (1104,),
 (1105,),
 (1108,),
 (1109,),
 (1110,),
 (1111,),
 (1114,),
 (1115,),
 (1117,),
 (1118,),
 (1119,),
 (1120,),
 (1121,),
 (1122,),
 (1123,),
 (1124,),
 (1125,),
 (1126,),
 (1127,),
 (1128,),
 (1129,),
 (1130,),
 (1131,),
 (1132,),
 (1133,),
 (1134,),
 (1135,),
 (1136,),
 (1137,),
 (1138,),
 (1139,),
 (1140,),
 (1141,),
 (1142,),
 (1143,),
 (1144,),
 (1145,),
 (1146,),
 (1147,),
 (1148,),
 (1149,),
 (1150,),
 (1151,),
 (1152,),
 (1153,),
 (1154,),
 (1155,),
 (1156,),
 (1157,),
 (1158,),
 (1159,),
 (1160,),
 (1161,),
 (1162,),
 (1163,),
 (1164,),
 (1165,),
 (1166,),
 (1167,),
 (1168,),
 (1169,),
 (1170,),
 (1171,),
 (1172,),
 (1173,),
 (1174,),
 (1175,),
 (1176,),
 (1177,),
 (1178,),
 (1179,),
 (1180,),
 (1181,),
 (1182,),
 (1183,),
 (1184,),
 (1185,),
 (1186,),
 (1187,),
 (1188,),
 (1189,),
 (1195,),
 (1197,),
 (1199,),
 (1204,),
 (1205,),
 (1209,),
 (1211,),
 (1212,),
 (1214,),
 (1215,),
 (1218,),
 (1220,),
 (1221,),
 (1223,),
 (1224,),
 (1231,),
 (1233,),
 (1240,),
 (1250,),
 (1251,),
 (1259,),
 (1266,),
 (1268,),
 (1269,),
 (1270,),
 (1271,),
 (1272,),
 (1273,),
 (1274,),
 (1275,),
 (1276,),
 (1278,),
 (1279,),
 (1280,),
 (1284,),
 (1285,),
 (1292,),
 (1296,),
 (1298,),
 (1306,),
 (1310,),
 (1312,),
 (1314,),
 (1324,),
 (1325,),
 (1326,),
 (1327,),
 (1328,),
 (1329,),
 (1330,),
 (1331,),
 (1332,),
 (1333,),
 (1334,),
 (1341,),
 (1343,),
 (1344,),
 (1348,),
 (1351,),
 (1356,),
 (1361,),
 (1362,),
 (1363,),
 (1364,),
 (1365,),
 (1366,),
 (1367,),
 (1368,),
 (1369,),
 (1370,),
 (1372,),
 (1378,),
 (1379,),
 (1380,),
 (1386,),
 (1387,),
 (1392,),
 (1405,),
 (1414,),
 (1415,),
 (1416,),
 (1417,),
 (1418,),
 (1419,),
 (1420,),
 (1421,),
 (1422,),
 (1423,),
 (1424,),
 (1425,),
 (1426,),
 (1427,),
 (1428,),
 (1429,),
 (1430,),
 (1431,),
 (1432,),
 (1433,),
 (1434,),
 (1435,),
 (1436,),
 (1437,),
 (1438,),
 (1439,),
 (1440,),
 (1441,),
 (1442,),
 (1443,),
 (1445,),
 (1448,),
 (1449,),
 (1453,),
 (1454,),
 (1455,),
 (1456,),
 (1457,),
 (1458,),
 (1459,),
 (1460,),
 (1461,),
 (1462,),
 (1463,),
 (1464,),
 (1465,),
 (1466,),
 (1467,),
 (1468,),
 (1469,),
 (1470,),
 (1471,),
 (1472,),
 (1473,),
 (1474,),
 (1475,),
 (1476,),
 (1477,),
 (1478,),
 (1479,),
 (1480,),
 (1481,),
 (1482,),
 (1483,),
 (1484,),
 (1485,),
 (1486,),
 (1487,),
 (1488,),
 (1489,),
 (1490,),
 (1491,),
 (1492,),
 (1493,),
 (1494,),
 (1495,),
 (1496,),
 (1498,),
 (1500,),
 (1501,),
 (1502,),
 (1503,),
 (1508,),
 (1511,),
 (1512,),
 (1518,),
 (1520,),
 (1521,),
 (1522,),
 (1523,),
 (1524,),
 (1525,),
 (1526,),
 (1527,),
 (1528,),
 (1529,),
 (1530,),
 (1531,),
 (1546,),
 (1547,),
 (1549,),
 (1550,),
 (1551,),
 (1552,),
 (1553,),
 (1554,),
 (1555,),
 (1556,),
 (1557,),
 (1558,),
 (1559,),
 (1560,),
 (1561,),
 (1562,),
 (1563,),
 (1564,),
 (1565,),
 (1566,),
 (1567,),
 (1568,),
 (1569,),
 (1570,),
 (1571,),
 (1572,),
 (1573,),
 (1574,),
 (1575,),
 (1576,),
 (1579,),
 (1580,),
 (1581,),
 (1582,),
 (1583,),
 (1585,),
 (1586,),
 (1591,),
 (1592,),
 (1598,),
 (1600,),
 (1601,),
 (1602,),
 (1604,),
 (1610,),
 (1614,),
 (1615,),
 (1617,),
 (1619,),
 (1620,),
 (1622,),
 (1623,),
 (1626,),
 (1629,),
 (1630,),
 (1636,),
 (1637,),
 (1641,),
 (1646,),
 (1648,),
 (1649,),
 (1650,),
 (1652,),
 (1654,),
 (1655,),
 (1656,),
 (1657,),
 (1658,),
 (1660,),
 (1666,),
 (1668,),
 (1669,),
 (1670,),
 (1677,),
 (1679,),
 (1686,),
 (1692,),
 (1696,),
 (1698,),
 (1699,),
 (1703,),
 (1704,),
 (1711,),
 (1712,),
 (1721,),
 (1725,),
 (1729,),
 (1733,),
 (1743,),
 (1744,),
 (1745,),
 (1746,),
 (1747,),
 (1748,),
 (1749,),
 (1750,),
 (1751,),
 (1752,),
 (1753,),
 (1754,),
 (1755,),
 (1756,),
 (1757,),
 (1758,),
 (1759,),
 (1760,),
 (1761,),
 (1762,),
 (1763,),
 (1764,),
 (1765,),
 (1766,),
 (1767,),
 (1768,),
 (1769,),
 (1770,),
 (1771,),
 (1772,),
 (1773,),
 (1774,),
 (1775,),
 (1776,),
 (1777,),
 (1778,),
 (1779,),
 (1780,),
 (1781,),
 (1782,),
 (1783,),
 (1784,),
 (1785,),
 (1786,),
 (1787,),
 (1788,),
 (1789,),
 (1790,),
 (1791,),
 (1793,),
 (1794,),
 (1796,),
 (1797,),
 (1798,),
 (1799,),
 (1800,),
 (1802,),
 (1805,),
 (1807,),
 (1809,),
 (1810,),
 (1814,),
 (1815,),
 (1816,),
 (1817,),
 (1819,),
 (1820,),
 (1823,),
 (1826,),
 (1827,),
 (1828,),
 (1829,),
 (1830,),
 (1831,),
 (1832,),
 (1833,),
 (1834,),
 (1835,),
 (1836,),
 (1837,),
 (1838,),
 (1839,),
 (1843,),
 (1845,),
 (1846,),
 (1849,),
 (1850,),
 (1851,),
 (1852,),
 (1853,),
 (1854,),
 (1855,),
 (1856,),
 (1857,),
 (1858,),
 (1859,),
 (1860,),
 (1865,),
 (1871,),
 (1872,),
 (1875,),
 (1876,),
 (1877,),
 (1879,),
 (1880,),
 (1882,),
 (1883,),
 (1884,),
 (1885,),
 (1886,),
 (1887,),
 (1888,),
 (1889,),
 (1890,),
 (1891,),
 (1892,),
 (1896,),
 (1897,),
 (1900,),
 (1902,),
 (1903,),
 (1904,),
 (1905,),
 (1906,),
 (1907,),
 (1908,),
 (1909,),
 (1910,),
 (1911,),
 (1912,),
 (1913,),
 (1914,),
 (1915,),
 (1925,),
 (1928,),
 (1937,),
 (1938,),
 (1942,),
 (1943,),
 (1944,),
 (1945,),
 (1946,),
 (1947,),
 (1948,),
 (1949,),
 (1950,),
 (1951,),
 (1952,),
 (1953,),
 (1954,),
 (1955,),
 (1956,),
 (1969,),
 (1972,),
 (1973,),
 (1976,),
 (1977,),
 (1978,),
 (1979,),
 (1980,),
 (1981,),
 (1983,),
 (1984,),
 (1986,),
 (1987,),
 (1988,),
 (1989,),
 (1990,),
 (1991,),
 (1992,),
 (1993,),
 (1994,),
 (1995,),
 (1996,),
 (1997,),
 (1998,),
 (1999,),
 (2000,),
 (2001,),
 (2002,),
 (2003,),
 (2004,),
 (2005,),
 (2006,),
 (2007,),
 (2008,),
 (2009,),
 (2010,),
 (2011,),
 (2012,),
 (2013,),
 (2014,),
 (2041,),
 (2086,),
 (2093,),
 (2095,),
 (2097,),
 (2098,),
 (2099,),
 (2102,),
 (2106,),
 (2107,),
 (2108,),
 (2109,),
 (2110,),
 (2111,),
 (2112,),
 (2113,),
 (2115,),
 (2118,),
 (2120,),
 (2127,),
 (2130,),
 (2132,),
 (2149,),
 (2150,),
 (2151,),
 (2152,),
 (2153,),
 (2154,),
 (2155,),
 (2156,),
 (2157,),
 (2158,),
 (2159,),
 (2160,),
 (2161,),
 (2162,),
 (2163,),
 (2164,),
 (2165,),
 (2166,),
 (2167,),
 (2168,),
 (2169,),
 (2170,),
 (2171,),
 (2172,),
 (2173,),
 (2174,),
 (2175,),
 (2176,),
 (2177,),
 (2178,),
 (2179,),
 (2180,),
 (2181,),
 (2182,),
 (2183,),
 (2184,),
 (2185,),
 (2186,),
 (2187,),
 (2188,),
 (2189,),
 (2190,),
 (2191,),
 (2192,),
 (2194,),
 (2197,),
 (2199,),
 (2201,),
 (2202,),
 (2203,),
 (2204,),
 (2205,),
 (2206,),
 (2207,),
 (2208,),
 (2209,),
 (2210,),
 (2211,),
 (2212,),
 (2213,),
 (2214,),
 (2215,),
 (2216,),
 (2217,),
 (2220,),
 (2223,),
 (2225,),
 (2226,),
 (2227,),
 (2228,),
 (2229,),
 (2230,),
 (2231,),
 ...]

In [ ]:
%%sql

WITH invoice_first_track AS
    (
     SELECT
         il.invoice_id invoice_id,
         MIN(il.track_id) first_track_id
     FROM invoice_line il
     GROUP BY 1
    )

SELECT
    album_purchase,
    COUNT(invoice_id) number_of_invoices,
    CAST(count(invoice_id) AS FLOAT) / (
                                         SELECT COUNT(*) FROM invoice
                                      ) percent
FROM
    (
    SELECT
        ifs.*,
        CASE
            WHEN
                 (
                  SELECT t.track_id FROM track t
                  WHERE t.album_id = (
                                      SELECT t2.album_id FROM track t2
                                      WHERE t2.track_id = ifs.first_track_id
                                     ) 

                  EXCEPT 

                  SELECT il2.track_id FROM invoice_line il2
                  WHERE il2.invoice_id = ifs.invoice_id
                 ) IS NULL
             AND
                 (
                  SELECT il2.track_id FROM invoice_line il2
                  WHERE il2.invoice_id = ifs.invoice_id

                  EXCEPT 

                  SELECT t.track_id FROM track t
                  WHERE t.album_id = (
                                      SELECT t2.album_id FROM track t2
                                      WHERE t2.track_id = ifs.first_track_id
                                     ) 
                 ) IS NULL
             THEN "yes"
             ELSE "no"
         END AS "album_purchase"
     FROM invoice_first_track ifs
    )
GROUP BY album_purchase;

Done.

[('no', 500, 0.8143322475570033), ('yes', 114, 0.18566775244299674)]

In [ ]:
%%sql
SELECT
         il.invoice_id invoice_id,
         MIN(il.track_id) first_track_id
     FROM invoice_line il
     GROUP BY 1

Done.

[(1, 1158),
 (2, 201),
 (3, 2516),
 (4, 748),
 (5, 1986),
 (6, 30),
 (7, 42),
 (8, 81),
 (9, 196),
 (10, 2663),
 (11, 610),
 (12, 92),
 (13, 2553),
 (14, 541),
 (15, 807),
 (16, 16),
 (17, 55),
 (18, 1027),
 (19, 105),
 (20, 60),
 (21, 13),
 (22, 383),
 (23, 1),
 (24, 1146),
 (25, 32),
 (26, 85),
 (27, 1280),
 (28, 36),
 (29, 479),
 (30, 33),
 (31, 2731),
 (32, 38),
 (33, 2542),
 (34, 610),
 (35, 6),
 (36, 153),
 (37, 698),
 (38, 154),
 (39, 184),
 (40, 108),
 (41, 153),
 (42, 13),
 (43, 918),
 (44, 3052),
 (45, 102),
 (46, 2639),
 (47, 8),
 (48, 58),
 (49, 146),
 (50, 1511),
 (51, 34),
 (52, 2664),
 (53, 207),
 (54, 1773),
 (55, 155),
 (56, 2254),
 (57, 2948),
 (58, 1029),
 (59, 198),
 (60, 46),
 (61, 2609),
 (62, 97),
 (63, 6),
 (64, 38),
 (65, 539),
 (66, 442),
 (67, 9),
 (68, 61),
 (69, 85),
 (70, 2307),
 (71, 2254),
 (72, 30),
 (73, 2391),
 (74, 1743),
 (75, 22),
 (76, 1020),
 (77, 15),
 (78, 33),
 (79, 1902),
 (80, 3400),
 (81, 545),
 (82, 54),
 (83, 1163),
 (84, 3455),
 (85, 1298),
 (86, 2291),
 (87, 1129),
 (88, 1995),
 (89, 1784),
 (90, 2554),
 (91, 94),
 (92, 1414),
 (93, 20),
 (94, 50),
 (95, 27),
 (96, 453),
 (97, 16),
 (98, 419),
 (99, 2591),
 (100, 996),
 (101, 83),
 (102, 33),
 (103, 1029),
 (104, 1508),
 (105, 751),
 (106, 2),
 (107, 1),
 (108, 58),
 (109, 340),
 (110, 81),
 (111, 48),
 (112, 1479),
 (113, 134),
 (114, 1479),
 (115, 84),
 (116, 21),
 (117, 4),
 (118, 3111),
 (119, 1556),
 (120, 17),
 (121, 32),
 (122, 28),
 (123, 2003),
 (124, 470),
 (125, 45),
 (126, 42),
 (127, 2),
 (128, 836),
 (129, 12),
 (130, 1573),
 (131, 920),
 (132, 2234),
 (133, 37),
 (134, 204),
 (135, 1221),
 (136, 1157),
 (137, 43),
 (138, 2271),
 (139, 781),
 (140, 468),
 (141, 2621),
 (142, 23),
 (143, 479),
 (144, 158),
 (145, 1422),
 (146, 1466),
 (147, 56),
 (148, 24),
 (149, 28),
 (150, 1021),
 (151, 605),
 (152, 1030),
 (153, 2406),
 (154, 2649),
 (155, 94),
 (156, 1882),
 (157, 3336),
 (158, 1050),
 (159, 153),
 (160, 36),
 (161, 55),
 (162, 899),
 (163, 768),
 (164, 913),
 (165, 59),
 (166, 56),
 (167, 484),
 (168, 58),
 (169, 18),
 (170, 157),
 (171, 1466),
 (172, 1185),
 (173, 2285),
 (174, 422),
 (175, 1755),
 (176, 1114),
 (177, 1039),
 (178, 1102),
 (179, 39),
 (180, 1150),
 (181, 1470),
 (182, 86),
 (183, 1033),
 (184, 3409),
 (185, 991),
 (186, 826),
 (187, 1037),
 (188, 1455),
 (189, 2191),
 (190, 833),
 (191, 24),
 (192, 130),
 (193, 2548),
 (194, 1476),
 (195, 51),
 (196, 1325),
 (197, 592),
 (198, 1121),
 (199, 2008),
 (200, 15),
 (201, 3288),
 (202, 1747),
 (203, 6),
 (204, 14),
 (205, 1829),
 (206, 224),
 (207, 470),
 (208, 151),
 (209, 1495),
 (210, 18),
 (211, 39),
 (212, 1121),
 (213, 2271),
 (214, 80),
 (215, 1019),
 (216, 461),
 (217, 2554),
 (218, 894),
 (219, 897),
 (220, 1745),
 (221, 19),
 (222, 1029),
 (223, 2621),
 (224, 20),
 (225, 32),
 (226, 1132),
 (227, 468),
 (228, 531),
 (229, 58),
 (230, 15),
 (231, 154),
 (232, 6),
 (233, 9),
 (234, 2562),
 (235, 1129),
 (236, 164),
 (237, 2375),
 (238, 2271),
 (239, 2254),
 (240, 1774),
 (241, 2289),
 (242, 61),
 (243, 54),
 (244, 1026),
 (245, 1015),
 (246, 55),
 (247, 2639),
 (248, 152),
 (249, 1470),
 (250, 435),
 (251, 30),
 (252, 1),
 (253, 1121),
 (254, 183),
 (255, 529),
 (256, 1491),
 (257, 2285),
 (258, 1990),
 (259, 29),
 (260, 77),
 (261, 58),
 (262, 77),
 (263, 62),
 (264, 1187),
 (265, 109),
 (266, 1170),
 (267, 1997),
 (268, 13),
 (269, 3144),
 (270, 23),
 (271, 2271),
 (272, 61),
 (273, 1479),
 (274, 402),
 (275, 268),
 (276, 3300),
 (277, 128),
 (278, 1468),
 (279, 1184),
 (280, 3081),
 (281, 1902),
 (282, 891),
 (283, 95),
 (284, 194),
 (285, 134),
 (286, 1748),
 (287, 2004),
 (288, 2),
 (289, 16),
 (290, 438),
 (291, 165),
 (292, 162),
 (293, 802),
 (294, 18),
 (295, 1491),
 (296, 1466),
 (297, 2207),
 (298, 34),
 (299, 1042),
 (300, 51),
 (301, 5),
 (302, 77),
 (303, 43),
 (304, 11),
 (305, 2178),
 (306, 49),
 (307, 38),
 (308, 2964),
 (309, 1094),
 (310, 29),
 (311, 32),
 (312, 58),
 (313, 1454),
 (314, 31),
 (315, 1445),
 (316, 1050),
 (317, 3288),
 (318, 26),
 (319, 62),
 (320, 3319),
 (321, 2607),
 (322, 13),
 (323, 1125),
 (324, 31),
 (325, 1943),
 (326, 135),
 (327, 6),
 (328, 481),
 (329, 3299),
 (330, 1133),
 (331, 36),
 (332, 476),
 (333, 1006),
 (334, 1942),
 (335, 2391),
 (336, 2358),
 (337, 804),
 (338, 1523),
 (339, 696),
 (340, 1051),
 (341, 1520),
 (342, 1679),
 (343, 161),
 (344, 1479),
 (345, 35),
 (346, 151),
 (347, 16),
 (348, 9),
 (349, 1712),
 (350, 1017),
 (351, 26),
 (352, 2433),
 (353, 162),
 (354, 1387),
 (355, 13),
 (356, 51),
 (357, 469),
 (358, 93),
 (359, 35),
 (360, 2367),
 (361, 1991),
 (362, 695),
 (363, 433),
 (364, 10),
 (365, 157),
 (366, 195),
 (367, 154),
 (368, 952),
 (369, 514),
 (370, 922),
 (371, 2410),
 (372, 529),
 (373, 139),
 (374, 469),
 (375, 1268),
 (376, 615),
 (377, 49),
 (378, 1056),
 (379, 2542),
 (380, 475),
 (381, 1133),
 (382, 43),
 (383, 486),
 (384, 152),
 (385, 1),
 (386, 45),
 (387, 337),
 (388, 999),
 (389, 3064),
 (390, 1988),
 (391, 80),
 (392, 1853),
 (393, 80),
 (394, 15),
 (395, 757),
 (396, 822),
 (397, 781),
 (398, 2506),
 (399, 1146),
 (400, 40),
 (401, 13),
 (402, 1127),
 (403, 52),
 (404, 1174),
 (405, 542),
 (406, 1460),
 (407, 2204),
 (408, 1043),
 (409, 1021),
 (410, 131),
 (411, 6),
 (412, 261),
 (413, 2690),
 (414, 1),
 (415, 29),
 (416, 1048),
 (417, 4),
 (418, 2755),
 (419, 33),
 (420, 999),
 (421, 1),
 (422, 82),
 (423, 7),
 (424, 1495),
 (425, 1483),
 (426, 43),
 (427, 23),
 (428, 1013),
 (429, 828),
 (430, 1788),
 (431, 160),
 (432, 94),
 (433, 27),
 (434, 27),
 (435, 426),
 (436, 77),
 (437, 301),
 (438, 151),
 (439, 423),
 (440, 88),
 (441, 1079),
 (442, 572),
 (443, 13),
 (444, 2229),
 (445, 411),
 (446, 1),
 (447, 2285),
 (448, 186),
 (449, 1479),
 (450, 424),
 (451, 3044),
 (452, 572),
 (453, 9),
 (454, 1986),
 (455, 836),
 (456, 6),
 (457, 1562),
 (458, 3473),
 (459, 226),
 (460, 51),
 (461, 160),
 (462, 6),
 (463, 38),
 (464, 38),
 (465, 149),
 (466, 73),
 (467, 154),
 (468, 2149),
 (469, 2232),
 (470, 94),
 (471, 2368),
 (472, 697),
 (473, 2690),
 (474, 479),
 (475, 32),
 (476, 12),
 (477, 346),
 (478, 1479),
 (479, 419),
 (480, 1033),
 (481, 475),
 (482, 27),
 (483, 21),
 (484, 1424),
 (485, 1434),
 (486, 82),
 (487, 16),
 (488, 1902),
 (489, 1865),
 (490, 794),
 (491, 2558),
 (492, 532),
 (493, 536),
 (494, 3288),
 (495, 1019),
 (496, 1),
 (497, 1141),
 (498, 1780),
 (499, 1009),
 (500, 46),
 (501, 1466),
 (502, 158),
 (503, 409),
 (504, 4),
 (505, 3424),
 (506, 1479),
 (507, 82),
 (508, 152),
 (509, 26),
 (510, 2285),
 (511, 149),
 (512, 807),
 (513, 93),
 (514, 1176),
 (515, 2696),
 (516, 1039),
 (517, 36),
 (518, 1551),
 (519, 477),
 (520, 16),
 (521, 992),
 (522, 800),
 (523, 79),
 (524, 444),
 (525, 6),
 (526, 436),
 (527, 36),
 (528, 1479),
 (529, 3375),
 (530, 2231),
 (531, 2650),
 (532, 63),
 (533, 2165),
 (534, 10),
 (535, 1033),
 (536, 419),
 (537, 1853),
 (538, 426),
 (539, 3284),
 (540, 3467),
 (541, 48),
 (542, 1121),
 (543, 707),
 (544, 421),
 (545, 225),
 (546, 150),
 (547, 901),
 (548, 4),
 (549, 61),
 (550, 1122),
 (551, 1121),
 (552, 904),
 (553, 2102),
 (554, 517),
 (555, 1415),
 (556, 2461),
 (557, 608),
 (558, 103),
 (559, 900),
 (560, 1025),
 (561, 739),
 (562, 44),
 (563, 1617),
 (564, 1129),
 (565, 21),
 (566, 1788),
 (567, 432),
 (568, 17),
 (569, 6),
 (570, 1521),
 (571, 93),
 (572, 1134),
 (573, 21),
 (574, 85),
 (575, 897),
 (576, 9),
 (577, 23),
 (578, 2664),
 (579, 3),
 (580, 79),
 (581, 3375),
 (582, 891),
 (583, 3467),
 (584, 2962),
 (585, 49),
 (586, 20),
 (587, 94),
 (588, 18),
 (589, 2271),
 (590, 1362),
 (591, 162),
 (592, 465),
 (593, 57),
 (594, 476),
 (595, 46),
 (596, 12),
 (597, 46),
 (598, 1000),
 (599, 19),
 (600, 1006),
 (601, 14),
 (602, 164),
 (603, 481),
 (604, 1755),
 (605, 1128),
 (606, 2003),
 (607, 30),
 (608, 3060),
 (609, 1636),
 (610, 814),
 (611, 57),
 (612, 2204),
 (613, 1126),
 (614, 2650)]